service: bot-telegram-cripto-report

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  criptoreport:
    handler: handler.criptoreport
    events:
      - http:
          path: report
          method: get
          cors: false